import numpy as np
#zeros function
zero=np.zeros(5)
print(zero)
#double dimension zeros
mat_2d=np.zeros((3,3))
print(mat_2d)
#ones function
one=np.ones(4)
print(one)
#double dimension ones
matr_2d=np.ones((3,3))
print(matr_2d)
#random array
arr_randinteger=np.random.randint(1,50,10)
print(arr_randinteger)
#reshaping functions
arr=np.arange(1,21)
print(arr)
arr_2d=arr.reshape(4,5)
print(arr_2d)
arr_randintegers=np.random.randint(1,100,36)
print(arr_randintegers)
arr_randintegers=arr_randintegers.reshape(6,6)
print(arr_randintegers)
print(arr_randintegers.min())
print(arr_randintegers.max())
print(arr_randintegers.argmin())
print(arr_randintegers.argmax())
#Generate 20 random numbers from 1-99
r_numbers=np.random.randint(1,100,20)
print(r_numbers)
array_2d=r_numbers.reshape(4,5)
print(array_2d)
print("Dimesions",array_2d.shape)
print("Size",array_2d.size)
print(f'Memory size {(array_2d.size)*array_2d.itemsize} bytes')
#comparison of array
x=np.array([3,5])
y=np.array([2,5])
print("Comparison greater (x,y)")
print(np.greater(x,y))
x=np.array([3,5])
y=np.array([2,5])
print("Comparison less (x,y)")
print(np.less(x,y))
x=np.array([3,5])
y=np.array([2,5])
print("Comparison greater or equal (x,y)")
print(np.greater_equal(x,y))
x=np.array([3,5])
y=np.array([2,5])
print("Comparison less or equal (x,y)")
print(np.less_equal(x,y))